### ISSUE TITLE
Explicit vs hierarchical (your) architecture

### ISSUE THREAD

**Issue by AxMM** [NVIDIA/semantic-segmentation#162]
Hi, thank you for your amazing work.
I need some help, please.

I am trying to make inference to compare results between explicit vs hierarchical (your) architecture. In main branch.

For your hierarchical architecture (HRNet + OCR + multi-scale attention), I am doing this
```yml
HPARAMS: [
  {
   dataset: mydataset,
   cv: 0,
   syncbn: true,
   apex: true,
   fp16: true,
   bs_val: 1,
   eval: val,
   n_scales: "0.5,1.0,2.0",
   snapshot: "/dl/hierarchical/logs/train_mydataset_cv0/ocrnet.HRNet_Mscale_granite-waxbill_2021.09.03_04.07/best_checkpoint_ep130.pth",
   arch: ocrnet.HRNet_Mscale,
   result_dir: LOGDIR,
   dump_assets: true,
   dump_all_images: true,
   multi_scale_inference: true,
   log_msinf_to_tb: true,
  },
]
```

For my understanding you have: 

- HRNet + OCR + multi-scale attention (in ocrnet.py file)
- DeepLabV3+ + multi-scale attention (in attnscale.py file)

What can I do to run inference in explicit architecture? I think is HRNet + OCR + "explicit attention".
I can not find a way to run it. 
Can you give some tip?

Thanks.
